### ISSUE TITLE
Switch To Volumio Interface Disabled

### ISSUE THREAD

**Issue by uudruid74** [patrickkfkan/volumio-now-playing#1]
I am unable to switch to the volumio interface.  I have no idea why.  The volume is disabled, but it doesn't look like that class is affecting the Refresh or Switch buttons.  They just don't have any action associated with them.   Its not an anchor and it doesn't look like any events are associated, but I've not looked deeply.

**Comment by patrickkfkan** [comment]
Hi there. Do you have Mixer set to 'None'? If so, then it's a known bug which will be fixed in the next version.

**Comment by uudruid74** [comment]
Yes, mixer is set to none as I use my AVR for volume control.  Thanks

**Comment by patrickkfkan** [comment]
Fixed in v0.1.4
