### ISSUE TITLE
No button for "Volumio Kiosk (Local Display)"

### ISSUE THREAD

**Issue by happyfewNL** [patrickkfkan/volumio-now-playing#2]
First, thanks a lot for all your good work with Volumio.

I have installed your plugin in Volumio 3.179 to display 'Now playing' on my Chromecast with Google TV.
It works fine and looks great but there's no button "Now playing" and just an error 'Kiosk script not detected or could not be read.'

What am I doing wrong?

Any help would very much be appreciated !

Greetings Jan

**Comment by patrickkfkan** [comment]
Do you have a screen connected to your Volumio and, if so, did you install the Touch Display plugin?

**Comment by happyfewNL** [comment]
Hi, first excuses for this late reply. I've been busy with other things....
As you suggested I installed the Touch Display plugin and everything is working !
Thanks for your advice.
