### ISSUE TITLE
Support for accented characters?

### ISSUE THREAD

**Issue by i0466lt** [patrickkfkan/volumio-now-playing#7]
Hello,
the accented characters like  "à è Ü" aren't displayed in now playing screen.

Maybe it's my fault, but I cant find if is possible to set characters encodings. UTF8 will be great!

Thanx,
Ste

**Comment by patrickkfkan** [comment]
Hi there,

For song titles, the font is "Noto Sans Display" which is Unicode. For other stuff like album and artist names, the font is "Roboto".  Do both of these not show up correctly?

![image](https://github.com/patrickkfkan/volumio-now-playing/assets/55383971/a349877c-db18-4cf3-a46e-264d02031b95)

**Comment by i0466lt** [comment]
Thanx for the feedback, the behavior is pretty weird.
Today all is ok, all latin characters are displayed correctly.

The only thing that I've made is `apt  upgrade` and reboot. Maybe was something related to the os.

Thanx again for your reply,
Stefano
