### ISSUE TITLE
Custom font sizes causing Tidal logo to be huge

### ISSUE THREAD

**Issue by hsmiles** [patrickkfkan/volumio-now-playing#9]
Hi,
Love the plugin overall, but I'm having some issues with customising the font sizes. I'm using a 5" 800x400 display and want to make the fonts a little larger, but when I try to customise the font sizes the Tidal (or FLAC) logo becomes huge, and takes up most of the space. It doesn't seem to matter what size I make any of the fonts it stays the same.

![P_20231014_101108](https://github.com/patrickkfkan/volumio-now-playing/assets/109637296/dc9b5382-0eca-490d-b20d-9d613a4c01a4)

Also I'm not sure what is meant to happen, but when I try to view the preview it has the frame, but not content is shown.

![Screenshot 2023-10-14 104417](https://github.com/patrickkfkan/volumio-now-playing/assets/109637296/3d7008c8-2bfa-4ded-b601-2dcca1ff26e5)

**Comment by patrickkfkan** [comment]
You probably did not specify a unit for the font size, e.g. `14px`

**Comment by hsmiles** [comment]
Thanks, you're right, that fixed it.
